stages:
  build_dataset:
    cmd: python src/tourism_api/pipeline/build_dataset.py
    deps:
      - src/tourism_api/pipeline/build_dataset.py
    outs:
      - data/india_tourism.csv

  train:
    cmd: python src/tourism_api/pipeline/train.py
    deps:
      - src/tourism_api/pipeline/train.py
      - data/india_tourism.csv
    outs:
      - models/tourism_model.joblib
      - models/lookup_table.pkl
    metrics:
      - models/metrics.json:
          cache: false
