apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mlflow-db-secret-provider
  namespace: mlflow
spec:
  provider: aws
  parameters:
    region: "us-west-2"
    objects: |
      - objectName: "arn:aws:secretsmanager:us-west-2:992382469397:secret:sandbox-eks/mlflow/db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "DB_USERNAME"
          - path: "password"
            objectAlias: "DB_PASSWORD"
          - path: "dbname"
            objectAlias: "DB_NAME"
          - path: "endpoint"
            objectAlias: "DB_ENDPOINT"
  secretObjects:
    - secretName: mlflow-db-secret
      type: Opaque
      data:
        - objectName: "DB_USERNAME"
          key: DB_USERNAME
        - objectName: "DB_PASSWORD"
          key: DB_PASSWORD
        - objectName: "DB_NAME"
          key: DB_NAME
        - objectName: "DB_ENDPOINT"
          key: DB_ENDPOINT