apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mlflow-db-secret-provider
  namespace: mlflow
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "<project_name>/mlflow/db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "DB_USERNAME"
          - path: "password"
            objectAlias: "DB_PASSWORD"
          - path: "dbname"
            objectAlias: "DB_NAME"
  secretObjects:
    - secretName: mlflow-db-secret
      type: Opaque
      data:
        - objectName: "DB_USERNAME"
          key: DB_USERNAME
        - objectName: "DB_PASSWORD"
          key: DB_PASSWORD
        - objectName: "DB_NAME"
          key: DB_NAME